{{- if gt (len .Values.targetNamespaces) 0 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-pod-handler
rules:
- apiGroups:
  - ""  # core API group
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
  - "delete"
{{- end }}